add try except for client connection
api offline error fix. added try except block for api connection
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='spamapi.bolverblitz.net', port=443): Max retries exceeded with url: //tokens/self (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fbd4aa96eb8>: Failed to establish a new connection: [Errno -2] Name or service not known',))